project:
  type: website
  output-dir: _site

website:
  title: "Control Systems"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Chapter 1 — Mathematical Foundations"
        contents:
          - href: 01_mathematical_foundations/overview.qmd
            text: "Overview"
          - href: 01_mathematical_foundations/1.1_linear_algebra.md
            text: "1.1 Linear Algebra"
          - href: 01_mathematical_foundations/1.2_matrix_factorizations.md
            text: "1.2 Matrix Factorizations"

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
